/**
 * Unified Song Loader (Auto-generated)
 *
 * This file is generated by scripts/migrate_and_deduplicate.py.
 * Do not edit it manually.
 */

import type { PhomuSong } from '@/types/song';
import packMetadata from './packs.json';

import A1 from './A1.json';
import A2 from './A2.json';
import A3 from './A3.json';
import A4 from './A4.json';
import A5 from './A5.json';
import A6 from './A6.json';
import A7 from './A7.json';
import A8 from './A8.json';
import A9 from './A9.json';
import A10 from './A10.json';
import A11 from './A11.json';
import B1 from './B1.json';
import B2 from './B2.json';
import B3 from './B3.json';
import B4 from './B4.json';
import B5 from './B5.json';
import B6 from './B6.json';
import B7 from './B7.json';
import B8 from './B8.json';
import B9 from './B9.json';
import C1 from './C1.json';
import C2 from './C2.json';
import C3 from './C3.json';
import C4 from './C4.json';
import C5 from './C5.json';
import C6 from './C6.json';
import C7 from './C7.json';
import C8 from './C8.json';
import D1 from './D1.json';
import D2 from './D2.json';
import D3 from './D3.json';
import D4 from './D4.json';
import D5 from './D5.json';
import D6 from './D6.json';
import D7 from './D7.json';
import D8 from './D8.json';
import D9 from './D9.json';
import E1 from './E1.json';
import E2 from './E2.json';
import E3 from './E3.json';
import E4 from './E4.json';
import E5 from './E5.json';
import F1 from './F1.json';
import F2 from './F2.json';
import F3 from './F3.json';
import F4 from './F4.json';
import G1 from './G1.json';
import G2 from './G2.json';
import G3 from './G3.json';
import G4 from './G4.json';
import G5 from './G5.json';
import H1 from './H1.json';
import H2 from './H2.json';
import H3 from './H3.json';
import I1 from './I1.json';
import I2 from './I2.json';
import J1 from './J1.json';
import J2 from './J2.json';
import J3 from './J3.json';
import J4 from './J4.json';
import J5 from './J5.json';
import J6 from './J6.json';
import J7 from './J7.json';
import J8 from './J8.json';
import J9 from './J9.json';
import J10 from './J10.json';
import K1 from './K1.json';
import K2 from './K2.json';
import K3 from './K3.json';
import K4 from './K4.json';
import K5 from './K5.json';
import L1 from './L1.json';
import L2 from './L2.json';
import L3 from './L3.json';
import L4 from './L4.json';
import L5 from './L5.json';
import L6 from './L6.json';
import L7 from './L7.json';
import M1 from './M1.json';
import M2 from './M2.json';
import M3 from './M3.json';
import M4 from './M4.json';
import M5 from './M5.json';
import M6 from './M6.json';
import M7 from './M7.json';
import M8 from './M8.json';
import M9 from './M9.json';
import N1 from './N1.json';
import N2 from './N2.json';
import N3 from './N3.json';
import NUMBERS from './NUMBERS.json';
import O1 from './O1.json';
import O2 from './O2.json';
import OTHERS from './OTHERS.json';
import P1 from './P1.json';
import P2 from './P2.json';
import P3 from './P3.json';
import P4 from './P4.json';
import P5 from './P5.json';
import P6 from './P6.json';
import P7 from './P7.json';
import Q from './Q.json';
import R1 from './R1.json';
import R2 from './R2.json';
import R3 from './R3.json';
import R4 from './R4.json';
import R5 from './R5.json';
import R6 from './R6.json';
import R7 from './R7.json';
import R8 from './R8.json';
import R9 from './R9.json';
import S1 from './S1.json';
import S2 from './S2.json';
import S3 from './S3.json';
import S4 from './S4.json';
import S5 from './S5.json';
import S6 from './S6.json';
import S7 from './S7.json';
import S8 from './S8.json';
import S9 from './S9.json';
import S10 from './S10.json';
import T1 from './T1.json';
import T2 from './T2.json';
import T3 from './T3.json';
import T4 from './T4.json';
import T5 from './T5.json';
import T6 from './T6.json';
import T7 from './T7.json';
import T8 from './T8.json';
import T9 from './T9.json';
import T10 from './T10.json';
import T11 from './T11.json';
import T12 from './T12.json';
import U from './U.json';
import V1 from './V1.json';
import V2 from './V2.json';
import W1 from './W1.json';
import W2 from './W2.json';
import X from './X.json';
import Y from './Y.json';
import Z from './Z.json';
import ENNE from './Ñ.json';

/** All unique songs across all namespaces */
export const ALL_SONGS: PhomuSong[] = [
  ...( A1.songs as PhomuSong[] ),
  ...( A2.songs as PhomuSong[] ),
  ...( A3.songs as PhomuSong[] ),
  ...( A4.songs as PhomuSong[] ),
  ...( A5.songs as PhomuSong[] ),
  ...( A6.songs as PhomuSong[] ),
  ...( A7.songs as PhomuSong[] ),
  ...( A8.songs as PhomuSong[] ),
  ...( A9.songs as PhomuSong[] ),
  ...( A10.songs as PhomuSong[] ),
  ...( A11.songs as PhomuSong[] ),
  ...( B1.songs as PhomuSong[] ),
  ...( B2.songs as PhomuSong[] ),
  ...( B3.songs as PhomuSong[] ),
  ...( B4.songs as PhomuSong[] ),
  ...( B5.songs as PhomuSong[] ),
  ...( B6.songs as PhomuSong[] ),
  ...( B7.songs as PhomuSong[] ),
  ...( B8.songs as PhomuSong[] ),
  ...( B9.songs as PhomuSong[] ),
  ...( C1.songs as PhomuSong[] ),
  ...( C2.songs as PhomuSong[] ),
  ...( C3.songs as PhomuSong[] ),
  ...( C4.songs as PhomuSong[] ),
  ...( C5.songs as PhomuSong[] ),
  ...( C6.songs as PhomuSong[] ),
  ...( C7.songs as PhomuSong[] ),
  ...( C8.songs as PhomuSong[] ),
  ...( D1.songs as PhomuSong[] ),
  ...( D2.songs as PhomuSong[] ),
  ...( D3.songs as PhomuSong[] ),
  ...( D4.songs as PhomuSong[] ),
  ...( D5.songs as PhomuSong[] ),
  ...( D6.songs as PhomuSong[] ),
  ...( D7.songs as PhomuSong[] ),
  ...( D8.songs as PhomuSong[] ),
  ...( D9.songs as PhomuSong[] ),
  ...( E1.songs as PhomuSong[] ),
  ...( E2.songs as PhomuSong[] ),
  ...( E3.songs as PhomuSong[] ),
  ...( E4.songs as PhomuSong[] ),
  ...( E5.songs as PhomuSong[] ),
  ...( F1.songs as PhomuSong[] ),
  ...( F2.songs as PhomuSong[] ),
  ...( F3.songs as PhomuSong[] ),
  ...( F4.songs as PhomuSong[] ),
  ...( G1.songs as PhomuSong[] ),
  ...( G2.songs as PhomuSong[] ),
  ...( G3.songs as PhomuSong[] ),
  ...( G4.songs as PhomuSong[] ),
  ...( G5.songs as PhomuSong[] ),
  ...( H1.songs as PhomuSong[] ),
  ...( H2.songs as PhomuSong[] ),
  ...( H3.songs as PhomuSong[] ),
  ...( I1.songs as PhomuSong[] ),
  ...( I2.songs as PhomuSong[] ),
  ...( J1.songs as PhomuSong[] ),
  ...( J2.songs as PhomuSong[] ),
  ...( J3.songs as PhomuSong[] ),
  ...( J4.songs as PhomuSong[] ),
  ...( J5.songs as PhomuSong[] ),
  ...( J6.songs as PhomuSong[] ),
  ...( J7.songs as PhomuSong[] ),
  ...( J8.songs as PhomuSong[] ),
  ...( J9.songs as PhomuSong[] ),
  ...( J10.songs as PhomuSong[] ),
  ...( K1.songs as PhomuSong[] ),
  ...( K2.songs as PhomuSong[] ),
  ...( K3.songs as PhomuSong[] ),
  ...( K4.songs as PhomuSong[] ),
  ...( K5.songs as PhomuSong[] ),
  ...( L1.songs as PhomuSong[] ),
  ...( L2.songs as PhomuSong[] ),
  ...( L3.songs as PhomuSong[] ),
  ...( L4.songs as PhomuSong[] ),
  ...( L5.songs as PhomuSong[] ),
  ...( L6.songs as PhomuSong[] ),
  ...( L7.songs as PhomuSong[] ),
  ...( M1.songs as PhomuSong[] ),
  ...( M2.songs as PhomuSong[] ),
  ...( M3.songs as PhomuSong[] ),
  ...( M4.songs as PhomuSong[] ),
  ...( M5.songs as PhomuSong[] ),
  ...( M6.songs as PhomuSong[] ),
  ...( M7.songs as PhomuSong[] ),
  ...( M8.songs as PhomuSong[] ),
  ...( M9.songs as PhomuSong[] ),
  ...( N1.songs as PhomuSong[] ),
  ...( N2.songs as PhomuSong[] ),
  ...( N3.songs as PhomuSong[] ),
  ...( NUMBERS.songs as PhomuSong[] ),
  ...( O1.songs as PhomuSong[] ),
  ...( O2.songs as PhomuSong[] ),
  ...( OTHERS.songs as PhomuSong[] ),
  ...( P1.songs as PhomuSong[] ),
  ...( P2.songs as PhomuSong[] ),
  ...( P3.songs as PhomuSong[] ),
  ...( P4.songs as PhomuSong[] ),
  ...( P5.songs as PhomuSong[] ),
  ...( P6.songs as PhomuSong[] ),
  ...( P7.songs as PhomuSong[] ),
  ...( Q.songs as PhomuSong[] ),
  ...( R1.songs as PhomuSong[] ),
  ...( R2.songs as PhomuSong[] ),
  ...( R3.songs as PhomuSong[] ),
  ...( R4.songs as PhomuSong[] ),
  ...( R5.songs as PhomuSong[] ),
  ...( R6.songs as PhomuSong[] ),
  ...( R7.songs as PhomuSong[] ),
  ...( R8.songs as PhomuSong[] ),
  ...( R9.songs as PhomuSong[] ),
  ...( S1.songs as PhomuSong[] ),
  ...( S2.songs as PhomuSong[] ),
  ...( S3.songs as PhomuSong[] ),
  ...( S4.songs as PhomuSong[] ),
  ...( S5.songs as PhomuSong[] ),
  ...( S6.songs as PhomuSong[] ),
  ...( S7.songs as PhomuSong[] ),
  ...( S8.songs as PhomuSong[] ),
  ...( S9.songs as PhomuSong[] ),
  ...( S10.songs as PhomuSong[] ),
  ...( T1.songs as PhomuSong[] ),
  ...( T2.songs as PhomuSong[] ),
  ...( T3.songs as PhomuSong[] ),
  ...( T4.songs as PhomuSong[] ),
  ...( T5.songs as PhomuSong[] ),
  ...( T6.songs as PhomuSong[] ),
  ...( T7.songs as PhomuSong[] ),
  ...( T8.songs as PhomuSong[] ),
  ...( T9.songs as PhomuSong[] ),
  ...( T10.songs as PhomuSong[] ),
  ...( T11.songs as PhomuSong[] ),
  ...( T12.songs as PhomuSong[] ),
  ...( U.songs as PhomuSong[] ),
  ...( V1.songs as PhomuSong[] ),
  ...( V2.songs as PhomuSong[] ),
  ...( W1.songs as PhomuSong[] ),
  ...( W2.songs as PhomuSong[] ),
  ...( X.songs as PhomuSong[] ),
  ...( Y.songs as PhomuSong[] ),
  ...( Z.songs as PhomuSong[] ),
  ...( ENNE.songs as PhomuSong[] ),
];

/** Metadata for all packs (names, descriptions, etc.) */
export const PACKS_METADATA = packMetadata;

/** All available pack names extracted from metadata */
export const AVAILABLE_PACKS: string[] = Object.keys(packMetadata);

/** Helper to get songs for specific packs */
export function getSongsForPacks(packNames: string[]): PhomuSong[] {
  return ALL_SONGS.filter(song =>
    song.packs.some(p => packNames.includes(p))
  );
}
