/**
 * Unified Song Loader (Auto-generated)
 * 
 * This file is generated by scripts/migrate_and_deduplicate.py.
 * Do not edit it manually.
 */

import type { PhomuSong } from '@/types/song';
import packMetadata from './packs.json';

import A1 from './A1.json';
import A2 from './A2.json';
import B1 from './B1.json';
import B2 from './B2.json';
import C from './C.json';
import D1 from './D1.json';
import D2 from './D2.json';
import E from './E.json';
import F from './F.json';
import G from './G.json';
import H from './H.json';
import I from './I.json';
import J1 from './J1.json';
import J2 from './J2.json';
import K from './K.json';
import L from './L.json';
import M1 from './M1.json';
import M2 from './M2.json';
import N from './N.json';
import NUMBERS from './NUMBERS.json';
import O from './O.json';
import OTHERS from './OTHERS.json';
import P from './P.json';
import Q from './Q.json';
import R1 from './R1.json';
import R2 from './R2.json';
import S1 from './S1.json';
import S2 from './S2.json';
import T1 from './T1.json';
import T2 from './T2.json';
import U from './U.json';
import V from './V.json';
import W from './W.json';
import X from './X.json';
import Y from './Y.json';
import Z from './Z.json';
import ENNE from './Ñ.json';

/** All unique songs across all namespaces */
export const ALL_SONGS: PhomuSong[] = [
  ...( A1.songs as PhomuSong[] ),
  ...( A2.songs as PhomuSong[] ),
  ...( B1.songs as PhomuSong[] ),
  ...( B2.songs as PhomuSong[] ),
  ...( C.songs as PhomuSong[] ),
  ...( D1.songs as PhomuSong[] ),
  ...( D2.songs as PhomuSong[] ),
  ...( E.songs as PhomuSong[] ),
  ...( F.songs as PhomuSong[] ),
  ...( G.songs as PhomuSong[] ),
  ...( H.songs as PhomuSong[] ),
  ...( I.songs as PhomuSong[] ),
  ...( J1.songs as PhomuSong[] ),
  ...( J2.songs as PhomuSong[] ),
  ...( K.songs as PhomuSong[] ),
  ...( L.songs as PhomuSong[] ),
  ...( M1.songs as PhomuSong[] ),
  ...( M2.songs as PhomuSong[] ),
  ...( N.songs as PhomuSong[] ),
  ...( NUMBERS.songs as PhomuSong[] ),
  ...( O.songs as PhomuSong[] ),
  ...( OTHERS.songs as PhomuSong[] ),
  ...( P.songs as PhomuSong[] ),
  ...( Q.songs as PhomuSong[] ),
  ...( R1.songs as PhomuSong[] ),
  ...( R2.songs as PhomuSong[] ),
  ...( S1.songs as PhomuSong[] ),
  ...( S2.songs as PhomuSong[] ),
  ...( T1.songs as PhomuSong[] ),
  ...( T2.songs as PhomuSong[] ),
  ...( U.songs as PhomuSong[] ),
  ...( V.songs as PhomuSong[] ),
  ...( W.songs as PhomuSong[] ),
  ...( X.songs as PhomuSong[] ),
  ...( Y.songs as PhomuSong[] ),
  ...( Z.songs as PhomuSong[] ),
  ...( ENNE.songs as PhomuSong[] ),
];

/** Metadata for all packs (names, descriptions, etc.) */
export const PACKS_METADATA = packMetadata;

/** All available pack names extracted from metadata */
export const AVAILABLE_PACKS: string[] = Object.keys(packMetadata);

/** Helper to get songs for specific packs */
export function getSongsForPacks(packNames: string[]): PhomuSong[] {
  return ALL_SONGS.filter(song => 
    song.packs.some(p => packNames.includes(p))
  );
}
