import json
import re

# Consolidate extracted data from the spreadsheet report into a structured JSON
# Note: This is based on the data extracted by the browser subagent in previous turn.

raw_corrections = [
    {"pack": "2000s Pop & RnB", "artist": "Rihanna ft. Jay-Z", "track": "Umbrella", "year": 2007, "new_link": "https://www.youtube.com/watch?v=CvBfHwUxHIk&list=RDCvBfHwUxHIk"},
    {"pack": "2010s & 2020s Chart Toppers", "artist": "Billie Eilish", "track": "Bad guy", "year": 2019, "new_link": "https://www.youtube.com/watch?v=DyDfgMOUjCI&list=RDDyDfgMOUjCI"},
    {"pack": "60s & 70s Soul & Rock Legends", "artist": "ABBA", "track": "Dancing Queen", "year": 1976, "new_link": "https://www.youtube.com/watch?v=xFrGuyw1V8s&list=RDxFrGuyw1V8s"},
    {"pack": "60s & 70s Soul & Rock Legends", "artist": "Fleetwood Mac", "track": "Dreams", "year": 1977, "new_link": "https://www.youtube.com/watch?v=Y3ywicffOj4&list=RDY3ywicffOj4"},
    {"pack": "60s & 70s Soul & Rock Legends", "artist": "Simon & Garfunkel", "track": "Bridge Over Troubled Water", "year": 1970, "new_link": "https://www.youtube.com/watch?v=4G-YQA_bsOU&list=RD4G-YQA_bsOU"},
    {"pack": "80s Flashback", "artist": "The Police", "track": "Every Breath You Take", "year": 1983, "new_link": "https://www.youtube.com/watch?v=OMOGaugKpzs&list=RDOMOGaugKpzs"},
    {"pack": "80s Flashback", "artist": "The Police", "track": "Roxanne", "year": 1978, "new_link": "https://www.youtube.com/watch?v=3T1c7GkzRQQ&list=RD3T1c7GkzRQQ"},
    {"pack": "80s-pop", "artist": "Madonna", "track": "Like a Virgin", "year": 1984, "new_link": "https://www.youtube.com/watch?v=s__rX_WL100&list=RDs__rX_WL100"},
    {"pack": "80s-pop", "artist": "Cyndi Lauper", "track": "Girls Just Want to Have Fun", "year": 1983, "new_link": "https://www.youtube.com/watch?v=PIb6AZdTr-A&list=RDPIb6AZdTr-A"},
    {"pack": "80s-pop", "artist": "Whitney Houston", "track": "I Wanna Dance with Somebody", "year": 1987, "new_link": "https://www.youtube.com/watch?v=eH3giaIzONA&list=RDeH3giaIzONA"},
    {"pack": "80s-pop", "artist": "George Michael", "track": "Careless Whisper", "year": 1984, "new_link": "https://www.youtube.com/watch?v=izGwDsrQ1eQ&list=RDizGwDsrQ1eQ"},
    {"pack": "80s-pop", "artist": "Duran Duran", "track": "Hungry Like the Wolf", "year": 1982, "new_link": "https://www.youtube.com/watch?v=oJL-lCzEXgI&list=RDoJL-lCzEXgI"},
    {"pack": "80s-pop", "artist": "The Police", "track": "Every Breath You Take", "year": 1983, "new_link": "https://www.youtube.com/watch?v=OMOGaugKpzs&list=RDOMOGaugKpzs"},
    {"pack": "80s-pop", "artist": "a-ha", "track": "Take On Me", "year": 1985, "new_link": "https://www.youtube.com/watch?v=djV11Xbc914&list=RDdjV11Xbc914"},
    {"pack": "80s-pop", "artist": "Journey", "track": "Don't Stop Believin'", "year": 1981, "new_link": "https://www.youtube.com/watch?v=1k8craCGpgs&list=RD1k8craCGpgs"},
    {"pack": "80s-pop", "artist": "Toto", "track": "Africa", "year": 1982, "new_link": "https://www.youtube.com/watch?v=FTQbiNvZqaY&list=RDFTQbiNvZqaY"},
    {"pack": "80s-pop", "artist": "Culture Club", "track": "Karma Chameleon", "year": 1983, "new_link": "https://www.youtube.com/watch?v=JmcA9LIIXWw&list=RDJmcA9LIIXWw"},
    {"pack": "80s-pop", "artist": "Soft Cell", "track": "Tainted Love", "year": 1981, "new_link": "https://www.youtube.com/watch?v=XZVpR3Pk-r8&list=RDXZVpR3Pk-r8"},
    {"pack": "80s-pop", "artist": "Depeche Mode", "track": "Just Can't Get Enough", "year": 1981, "new_link": "https://www.youtube.com/watch?v=_6FBfAQ-NDE&list=RD_6FBfAQ-NDE"},
    {"pack": "80s-pop", "artist": "Nena", "track": "99 Luftballons", "year": 1983, "new_link": "https://www.youtube.com/watch?v=Fpu5a0Bl8eY&list=RDFpu5a0Bl8eY"},
    {"pack": "80s-pop", "artist": "Alphaville", "track": "Forever Young", "year": 1984, "new_link": "https://www.youtube.com/watch?v=YHRvDo8rUoQ&list=RDYHRvDo8rUoQ"},
    {"pack": "80s-pop", "artist": "Modern Talking", "track": "You're My Heart, You're My Soul", "year": 1984, "new_link": "https://www.youtube.com/watch?v=4kHl4FoK1Ys&list=RD4kHl4FoK1Ys"},
    {"pack": "80s-pop", "artist": "Pet Shop Boys", "track": "West End Girls", "year": 1984, "new_link": "https://www.youtube.com/watch?v=Y0KQNn3aL4Q&list=RDY0KQNn3aL4Q"},
    {"pack": "80s-pop", "artist": "Bronski Beat", "track": "Smalltown Boy", "year": 1984, "new_link": "https://www.youtube.com/watch?v=88sARuFu-tc&list=RD88sARuFu-tc"},
    {"pack": "80s-pop", "artist": "Frankie Goes to Hollywood", "track": "Relax", "year": 1983, "new_link": "https://www.youtube.com/watch?v=Yem_iEHiyJ0&list=RDYem_iEHiyJ0"},
    {"pack": "80s-pop", "artist": "Bananarama", "track": "Venus", "year": 1986, "new_link": "https://www.youtube.com/watch?v=d4-1ASpdT1Y&list=RDd4-1ASpdT1Y"},
    {"pack": "80s-pop", "artist": "Belinda Carlisle", "track": "Heaven Is a Place on Earth", "year": 1987, "new_link": "https://www.youtube.com/watch?v=j2F4INQFjEI&list=RDj2F4INQFjEI"},
    {"pack": "80s-pop", "artist": "Baltimora", "track": "Tarzan Boy", "year": 1985, "new_link": "https://www.youtube.com/watch?v=--6CdAypJsQ&list=RD--6CdAypJsQ"},
    {"pack": "80s-pop", "artist": "Bonnie Tyler", "track": "Total Eclipse of the Heart", "year": 1983, "new_link": "https://www.youtube.com/watch?v=lcOxhH8N3Bo&list=RDlcOxhH8N3Bo"},
    {"pack": "80s-pop", "artist": "Kenny Loggins", "track": "Footloose", "year": 1984, "new_link": "https://www.youtube.com/watch?v=ltrMfT4Qz5Y&list=RDltrMfT4Qz5Y"},
    {"pack": "80s-pop", "artist": "Bill Medley & Jennifer Warnes", "track": "(I've Had) The Time of My Life", "year": 1987, "new_link": "https://www.youtube.com/watch?v=4BQLE_RrTSU&list=RD4BQLE_RrTSU"},
    {"pack": "80s-pop", "artist": "Survivor", "track": "Eye of the Tiger", "year": 1982, "new_link": "https://www.youtube.com/watch?v=btPJPFnesV4&list=RDbtPJPFnesV4"},
    {"pack": "80s-pop", "artist": "Simple Minds", "track": "Don't You (Forget About Me)", "year": 1985, "new_link": "https://www.youtube.com/watch?v=CdqoNKCCt7A&list=RDCdqoNKCCt7A"},
    {"pack": "80s-pop", "artist": "Spandau Ballet", "track": "TRUE", "year": 1983, "new_link": "https://www.youtube.com/watch?v=AR8D2yqgQ1U&list=RDAR8D2yqgQ1U"},
    {"pack": "90s Unplugged", "artist": "Sheryl Crow", "track": "All I Wanna Do", "year": 1993, "new_link": "https://www.youtube.com/watch?v=ClbmWkbocoY&list=RDClbmWkbocoY"},
    {"pack": "90s Unplugged", "artist": "Soul Asylum", "track": "Runaway Train", "year": 1992, "new_link": "https://www.youtube.com/watch?v=NRtvqT_wMeY&list=RDNRtvqT_wMeY"},
    {"pack": "90s Unplugged", "artist": "Eric Clapton", "track": "Layla (Unplugged)", "year": 1992, "new_link": "https://www.youtube.com/watch?v=-KG2O5PSCSs&list=RD-KG2O5PSCSs"},
    {"pack": "90s Unplugged", "artist": "Alice in Chains", "track": "Nutshell (Unplugged)", "year": 1996, "new_link": "https://www.youtube.com/watch?v=G23iLGhh9lo&list=RDG23iLGhh9lo"},
    {"pack": "90s Unplugged", "artist": "Pearl Jam", "track": "Black (Unplugged)", "year": 1992, "new_link": "https://www.youtube.com/watch?v=qgaRVvAKoqQ&list=RDqgaRVvAKoqQ"},
    {"pack": "classical-orchestral", "artist": "Ludwig van Beethoven", "track": "Symphony No. 5 (Fate)", "year": 1808, "new_link": "https://www.youtube.com/watch?v=jamsU8wICr0&list=RDjamsU8wICr0"},
    {"pack": "classical-orchestral", "artist": "Pyotr Ilyich Tchaikovsky", "track": "Swan Lake (Theme)", "year": 1876, "new_link": "https://www.youtube.com/watch?v=9cNQFB0TDfY&list=RD9cNQFB0TDfY"},
    {"pack": "classical-orchestral", "artist": "Edvard Grieg", "track": "In the Hall of the Mountain King", "year": 1875, "new_link": "https://www.youtube.com/watch?v=Y9dzyLvvIRs&list=RDY9dzyLvvIRs"},
    {"pack": "classical-orchestral", "artist": "Carl Orff", "track": "Carmina Burana (O Fortuna)", "year": 1936, "new_link": "https://www.youtube.com/watch?v=GXFSK0ogeg4&list=RDGXFSK0ogeg4"},
    {"pack": "classical-orchestral", "artist": "John Williams", "track": "Star Wars Main Title", "year": 1977, "new_link": "https://www.youtube.com/watch?v=54hoKbTWon4&list=RD54hoKbTWon4"},
    {"pack": "classical-orchestral", "artist": "Hans Zimmer / Klaus Badelt", "track": "He's a Pirate", "year": 2003, "new_link": "https://www.youtube.com/watch?v=jtGUQFky0KI&list=RDjtGUQFky0KI"},
    {"pack": "classical-orchestral", "artist": "Alan Silvestri", "track": "Back to the Future Theme", "year": 1985, "new_link": "https://www.youtube.com/watch?v=MxjbI294h0s&list=RDMxjbI294h0s"},
    {"pack": "classical-orchestral", "artist": "Ludovico Einaudi", "track": "Nuvole Bianche", "year": 2004, "new_link": "https://www.youtube.com/watch?v=VUCI-1vIbUo&list=RDVUCI-1vIbUo"},
    {"pack": "classical-orchestral", "artist": "Camille Saint-Saëns", "track": "Danse Macabre", "year": 1874, "new_link": "https://www.youtube.com/watch?v=71fZhMXlGT4&list=RD71fZhMXlGT4"},
    {"pack": "classical-orchestral", "artist": "Jean Sibelius", "track": "Finlandia", "year": 1899, "new_link": "https://www.youtube.com/watch?v=fE0RbPsC9uE&list=RDfE0RbPsC9uE"},
    {"pack": "classical-orchestral", "artist": "Jerry Goldsmith", "track": "Star Trek (Main Theme)", "year": 1979, "new_link": "https://www.youtube.com/watch?v=zI9YYe-jgHI&list=RDzI9YYe-jgHI"},
    {"pack": "classical-orchestral", "artist": "Thomas Newman", "track": "American Beauty (Any Other Name)", "year": 1999, "new_link": "https://www.youtube.com/watch?v=ucdz7A3s4Wc&list=RDucdz7A3s4Wc"},
    {"pack": "classical-orchestral", "artist": "James Horner", "track": "Rose (Titanic Theme)", "year": 1997, "new_link": "https://www.youtube.com/watch?v=iUH0dEe1jvA&list=RDiUH0dEe1jvA"},
    {"pack": "classical-orchestral", "artist": "Henry Mancini", "track": "Pink Panther Theme", "year": 1963, "new_link": "https://www.youtube.com/watch?v=wDoDYEFIMas&list=RDwDoDYEFIMas"},
    {"pack": "classical-orchestral", "artist": "Nino Rota", "track": "The Godfather (Main Title)", "year": 1972, "new_link": "https://www.youtube.com/watch?v=4HtPc9jzFuU&list=RD4HtPc9jzFuU"},
    {"pack": "country-folk", "artist": "Johnny Cash", "track": "Ring of Fire", "year": 1963, "new_link": "https://www.youtube.com/watch?v=1WaV2x8GXj0&list=RD1WaV2x8GXj0"},
    {"pack": "country-folk", "artist": "Chris Stapleton", "track": "Tennessee Whiskey", "year": 2015, "new_link": "https://www.youtube.com/watch?v=4zAThXFOy2c&list=RD4zAThXFOy2c"},
    {"pack": "country-folk", "artist": "Morgan Wallen", "track": "Whiskey Glasses", "year": 2018, "new_link": "https://www.youtube.com/watch?v=FjBp30kjzTc&list=RDFjBp30kjzTc"},
    {"pack": "country-folk", "artist": "Simon & Garfunkel", "track": "The Sound of Silence", "year": 1964, "new_link": "https://www.youtube.com/watch?v=NAEppFUWLfc&list=RDNAEppFUWLfc"},
    {"pack": "country-folk", "artist": "Joan Baez", "track": "Diamonds & Rust", "year": 1975, "new_link": "https://www.youtube.com/watch?v=IrVD0bP_ybg&list=RDIrVD0bP_ybg"},
    {"pack": "country-folk", "artist": "Kris Kristofferson", "track": "Me and Bobby McGee", "year": 1970, "new_link": "https://www.youtube.com/watch?v=k5qfT--sfE8&list=RDk5qfT--sfE8"},
    {"pack": "country-folk", "artist": "Patsy Cline", "track": "Crazy", "year": 1961, "new_link": "https://www.youtube.com/watch?v=YWKeuYcDAoo&list=RDYWKeuYcDAoo"},
    {"pack": "country-folk", "artist": "Billy Strings", "track": "Dust in a Baggie", "year": 2017, "new_link": "https://www.youtube.com/watch?v=qan4VRikfz8&list=RDqan4VRikfz8"},
    {"pack": "country-folk", "artist": "Zach Bryan", "track": "Something in the Orange", "year": 2022, "new_link": "https://www.youtube.com/watch?v=lA8F9sIhGdg&list=RDlA8F9sIhGdg"},
    {"pack": "Country, Jazz & Blues", "artist": "Johnny Cash", "track": "I Walk the Line", "year": 1956, "new_link": "https://www.youtube.com/watch?v=J-6fW66IUY4&list=RDJ-6fW66IUY4"},
    {"pack": "Country, Jazz & Blues", "artist": "Dolly Parton", "track": "Jolene", "year": 1973, "new_link": "https://www.youtube.com/watch?v=Ixrje2rXLMA&list=RDIxrje2rXLMA"},
    {"pack": "Country, Jazz & Blues", "artist": "Ella Fitzgerald", "track": "Summertime", "year": 1957, "new_link": "https://www.youtube.com/watch?v=2HJCN3upMHE&list=RD2HJCN3upMHE"},
    {"pack": "Country, Jazz & Blues", "artist": "Howlin' Wolf", "track": "Smokestack Lightnin'", "year": 1956, "new_link": "https://www.youtube.com/watch?v=VMUt8KdDtTY&list=RDVMUt8KdDtTY"},
    {"pack": "Country, Jazz & Blues", "artist": "Louis Jordan", "track": "Choo Choo Ch'Boogie", "year": 1946, "new_link": "https://www.youtube.com/watch?v=TftHrHOmSWc&list=RDTftHrHOmSWc"},
    {"pack": "Country, Jazz & Blues", "artist": "The Carter Family", "track": "Can the Circle Be Unbroken", "year": 1935, "new_link": "https://www.youtube.com/watch?v=pEFTdmk9g1c&list=RDpEFTdmk9g1c"},
    {"pack": "Country, Jazz & Blues", "artist": "Robert Cray", "track": "Smoking Gun", "year": 1986, "new_link": "https://www.youtube.com/watch?v=2gQEDwjhaDE&list=RD2gQEDwjhaDE"},
    {"pack": "Dance Floor Fillers", "artist": "Snap!", "track": "Rhythm Is a Dancer", "year": 1992, "new_link": "https://www.youtube.com/watch?v=JYIaWeVL1JM&list=RDJYIaWeVL1JM"},
    {"pack": "Dance Floor Fillers", "artist": "Fatboy Slim", "track": "The Rockafeller Skank", "year": 1998, "new_link": "https://www.youtube.com/watch?v=FMrIy9zm7QY&list=RDFMrIy9zm7QY"},
    {"pack": "Dance Floor Fillers", "artist": "Modjo", "track": "Lady (Hear Me Tonight)", "year": 2000, "new_link": "https://www.youtube.com/watch?v=mMfxI3r_LyA&list=RDmMfxI3r_LyA"},
    {"pack": "Dance Floor Fillers", "artist": "Avicii ft. Aloe Blacc", "track": "Wake Me Up", "year": 2013, "new_link": "https://www.youtube.com/watch?v=IcrbM1l_BoI&list=RDIcrbM1l_BoI"},
    {"pack": "Dance Floor Fillers", "artist": "Mark Ronson ft. Bruno Mars", "track": "Uptown Funk", "year": 2014, "new_link": "https://www.youtube.com/watch?v=OPf0YbXqDm0&list=RDOPf0YbXqDm0"},
    {"pack": "Dance Floor Fillers", "artist": "Justin Timberlake", "track": "Can't Stop the Feeling!", "year": 2016, "new_link": "https://www.youtube.com/watch?v=ru0K8uYEZWw&list=RDru0K8uYEZWw"},
    {"pack": "electronic-synth", "artist": "Tears for Fears", "track": "Everybody Wants to Rule the World", "year": 1985, "new_link": "https://www.youtube.com/watch?v=aGCdLKXNF3w&list=RBaGCdLKXNF3w"},
    {"pack": "electronic-synth", "artist": "Moby", "track": "Go", "year": 1991, "new_link": "https://www.youtube.com/watch?v=NLCHARjjrws&list=RDNLCHARjjrws"},
    {"pack": "electronic-synth", "artist": "Massive Attack", "track": "Unfinished Sympathy", "year": 1991, "new_link": "https://www.youtube.com/watch?v=ZWmrfgj0MZI&list=RDZWmrfgj0MZI"},
    {"pack": "electronic-synth", "artist": "Kavinsky", "track": "Nightcall", "year": 2010, "new_link": "https://www.youtube.com/watch?v=46qo_V1zcOM&list=RD46qo_V1zcOM"},
    {"pack": "electronic-synth", "artist": "Disclosure ft. Sam Smith", "track": "Latch", "year": 2012, "new_link": "https://www.youtube.com/watch?v=93ASUImTedo&list=RD93ASUImTedo"},
    {"pack": "electronic-synth", "artist": "Avicii", "track": "Levels", "year": 2011, "new_link": "https://www.youtube.com/watch?v=_ovdm2yX4MA&list=RD_ovdm2yX4MA"},
    {"pack": "electronic-synth", "artist": "Tears for Fears", "track": "Mad World (Original)", "year": 1983, "new_link": "https://www.youtube.com/watch?v=u1ZvPSpLxCg&list=RDu1ZvPSpLxCg"},
    {"pack": "electronic-synth", "artist": "Rick Astley", "track": "Never Gonna Give You Up", "year": 1987, "new_link": "https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=RDdQw4w9WgXcQ"},
    {"pack": "electronic-synth", "artist": "Kim Wilde", "track": "Kids in America", "year": 1981, "new_link": "https://www.youtube.com/watch?v=80TfG7C9azA&list=RD80TfG7C9azA"},
    {"pack": "electronic-synth", "artist": "Nena", "track": "99 Luftballons", "year": 1983, "new_link": "https://www.youtube.com/watch?v=Fpu5a0Bl8eY&list=RDFpu5a0Bl8eY"},
    {"pack": "electronic-synth", "artist": "Falco", "track": "Rock Me Amadeus", "year": 1985, "new_link": "https://www.youtube.com/watch?v=cVikZ8Oe_XA&list=RDcVikZ8Oe_XA"},
    {"pack": "electronic-synth", "artist": "Kygo ft. Conrad Sewell", "track": "Firestone", "year": 2014, "new_link": "https://www.youtube.com/watch?v=9Sc-ir2UwGU&list=RD9Sc-ir2UwGU"},
    {"pack": "electronic-synth", "artist": "David Guetta ft. Sia", "track": "Titanium", "year": 2011, "new_link": "https://www.youtube.com/watch?v=JRfuAukYTKg&list=RDJRfuAukYTKg"},
    {"pack": "Electronic & Techno", "artist": "Kraftwerk", "track": "Das Model", "year": 1978, "new_link": "https://www.youtube.com/watch?v=GEnx9xS79Lc&list=RDGEnx9xS79Lc"},
    {"pack": "Electronic & Techno", "artist": "Deadmau5", "track": "Strobe", "year": 2009, "new_link": "https://www.youtube.com/watch?v=tKi9Z-f6qX4&list=RDtKi9Z-f6qX4"},
    {"pack": "Electronic & Techno", "artist": "Zedd ft. Foxes", "track": "Clarity", "year": 2012, "new_link": "https://www.youtube.com/watch?v=IxxstCcJlsc&list=RDIxxstCcJlsc"},
    {"pack": "German Classics", "artist": "Nena", "track": "99 Luftballons", "year": 1983, "new_link": "https://www.youtube.com/watch?v=Fpu5a0Bl8eY&list=RDFpu5a0Bl8eY"},
    {"pack": "German Classics", "artist": "Falco", "track": "Rock Me Amadeus", "year": 1985, "new_link": "https://www.youtube.com/watch?v=cVikZ8Oe_XA&list=RDcVikZ8Oe_XA"},
    {"pack": "German Classics", "artist": "Die Toten Hosen", "track": "Hier kommt Alex", "year": 1988, "new_link": "https://www.youtube.com/watch?v=6z8o7qAIlIU&list=RD6z8o7qAIlIU"},
    {"pack": "German Classics", "artist": "Marius Müller-Westernhagen", "track": "Freiheit", "year": 1987, "new_link": "https://www.youtube.com/watch?v=agKE1TuUOuM&list=RDagKE1TuUOuM"},
    {"pack": "German Classics", "artist": "Fettes Brot", "track": "Jein", "year": 1996, "new_link": "https://www.youtube.com/watch?v=tcV7VN3l3bY&list=RDtcV7VN3l3bY"},
    {"pack": "German Classics", "artist": "Xavier Naidoo", "track": "Dieser Weg", "year": 2005, "new_link": "https://www.youtube.com/watch?v=9o4fDVYc_cQ&list=RD9o4fDVYc_cQ"},
    {"pack": "German Classics", "artist": "Peter Fox", "track": "Haus am See", "year": 2008, "new_link": "https://www.youtube.com/watch?v=Vgwkxa-uGcE&list=RDVgwkxa-uGcE"},
    {"pack": "German Classics", "artist": "Seeed", "track": "Ding", "year": 2005, "new_link": "https://www.youtube.com/watch?v=_yWU0lFghxU&list=RD_yWU0lFghxU"},
    {"pack": "Global Hits 1950-2026", "artist": "Chuck Berry", "track": "Johnny B. Goode", "year": 1958, "new_link": "https://www.youtube.com/watch?v=Y-9Y4CCIWnM&list=RDY-9Y4CCIWnM"},
    {"pack": "Global Hits 1950-2026", "artist": "David Bowie", "track": "Let's Dance", "year": 1983, "new_link": "https://www.youtube.com/watch?v=VbD_kBJc_gI&list=RDVbD_kBJc_gI"},
    {"pack": "Global Hits 1950-2026", "artist": "Justin Timberlake", "track": "Can't Stop the Feeling!", "year": 2016, "new_link": "https://www.youtube.com/watch?v=ru0K8uYEZWw&list=RDru0K8uYEZWw"},
    {"pack": "Global Hits 1950-2026", "artist": "Drake", "track": "One Dance", "year": 2016, "new_link": "https://www.youtube.com/watch?v=mym4sKoAnKs&list=RDmym4sKoAnKs"},
    {"pack": "Global Hits 1950-2026", "artist": "Luis Fonsi ft. Daddy Yankee", "track": "Despacito", "year": 2017, "new_link": "https://www.youtube.com/watch?v=kJQP7kiw5Fk&list=RDkJQP7kiw5Fk"},
    {"pack": "Global Hits 1950-2026", "artist": "The Weeknd", "track": "Blinding Lights", "year": 2019, "new_link": "https://www.youtube.com/watch?v=4NRXx6U8ABQ&list=RD4NRXx6U8ABQ"},
    {"pack": "grand-finale", "artist": "The Weeknd", "track": "Blinding Lights", "year": 2019, "new_link": "https://www.youtube.com/watch?v=4NRXx6U8ABQ&list=RD4NRXx6U8ABQ"},
    {"pack": "grand-finale", "artist": "Elton John & Dua Lipa", "track": "Cold Heart (PNAU Remix)", "year": 2021, "new_link": "https://www.youtube.com/watch?v=YjEqEHTgXLk&list=RDYjEqEHTgXLk"},
    {"pack": "grand-finale", "artist": "Lil Nas X", "track": "Montero (Call Me By Your Name)", "year": 2021, "new_link": "https://www.youtube.com/watch?v=6swmTBVI83k&list=RD6swmTBVI83k"},
    {"pack": "grand-finale", "artist": "Ed Sheeran", "track": "Shivers", "year": 2021, "new_link": "https://www.youtube.com/watch?v=Il0S8BoucSA&list=RDIl0S8BoucSA"},
    {"pack": "grand-finale", "artist": "Adele", "track": "Easy On Me", "year": 2021, "new_link": "https://www.youtube.com/watch?v=U3ASj1L6_sY&list=RDU3ASj1L6_sY"},
    {"pack": "grand-finale", "artist": "Måneskin", "track": "Beggin'", "year": 2017, "new_link": "https://www.youtube.com/watch?v=Xg72z08aTXY&list=RDXg72z08aTXY"},
    {"pack": "grand-finale", "artist": "Sabrina Carpenter", "track": "Espresso", "year": 2024, "new_link": "https://www.youtube.com/watch?v=eVli-tstM5E&list=RDeVli-tstM5E"},
    {"pack": "grand-finale", "artist": "Peggy Gou", "track": "(It Goes Like) Nanana", "year": 2023, "new_link": "https://www.youtube.com/watch?v=sCz5y84dwuA&list=RDsCz5y84dwuA"},
    {"pack": "grand-finale", "artist": "Mitski", "track": "My Love Mine All Mine", "year": 2023, "new_link": "https://www.youtube.com/watch?v=vx4kLgnFexo&list=RDvx4kLgnFexo"},
    {"pack": "grand-finale", "artist": "Jung Kook ft. Latto", "track": "Seven", "year": 2023, "new_link": "https://www.youtube.com/watch?v=KjK32vDk7mA&list=RDKjK32vDk7mA"},
    {"pack": "Hip Hop Essentials", "artist": "The Notorious B.I.G.", "track": "Juicy", "year": 1994, "new_link": "https://www.youtube.com/watch?v=_JZom_gVfuw&list=RD_JZom_gVfuw"},
    {"pack": "Hip Hop Essentials", "artist": "OutKast", "track": "Ms. Jackson", "year": 2000, "new_link": "https://www.youtube.com/watch?v=MYxAiK6VnXw&list=RDMYxAiK6VnXw"},
    {"pack": "Hip Hop Essentials", "artist": "Travis Scott", "track": "SICKO MODE", "year": 2018, "new_link": "https://www.youtube.com/watch?v=6ONRf7h3Mdk&list=RD6ONRf7h3Mdk"},
    {"pack": "Hip Hop Essentials", "artist": "Lil Nas X", "track": "Old Town Road", "year": 2019, "new_link": "https://www.youtube.com/watch?v=r7qovpFAGrQ&list=RDr7qovpFAGrQ"},
    {"pack": "Hip Hop Essentials", "artist": "Drake", "track": "God's Plan", "year": 2018, "new_link": "https://www.youtube.com/watch?v=xpVfcZ0ZcFM&list=RDxpVfcZ0ZcFM"},
    {"pack": "Hip Hop Essentials", "artist": "Cardi B", "track": "Bodak Yellow", "year": 2017, "new_link": "https://www.youtube.com/watch?v=PEGccV-NOm8&list=RDPEGccV-NOm8"},
    {"pack": "Hip Hop Essentials", "artist": "Megan Thee Stallion", "track": "Savage", "year": 2020, "new_link": "https://www.youtube.com/watch?v=eJEKHdvntPI&list=RDeJEKHdvntPI"},
    {"pack": "Indie & Alternative", "artist": "The White Stripes", "track": "Fell in Love with a Girl", "year": 2001, "new_link": "https://www.youtube.com/watch?v=fTH71AAxXmM&list=RDfTH71AAxXmM"},
    {"pack": "Indie & Alternative", "artist": "Gotye ft. Kimbra", "track": "Somebody That I Used To Know", "year": 2011, "new_link": "https://www.youtube.com/watch?v=8UVNT4wvIGY&list=RD8UVNT4wvIGY"},
    {"pack": "Indie & Alternative", "artist": "Imagine Dragons", "track": "Radioactive", "year": 2012, "new_link": "https://www.youtube.com/watch?v=ktvTqknDobU&list=RDktvTqknDobU"},
    {"pack": "jazz-blues", "artist": "Nina Simone", "track": "Feeling Good", "year": 1965, "new_link": "https://www.youtube.com/watch?v=oHRNrgDIJfo&list=RDoHRNrgDIJfo"},
    {"pack": "jazz-blues", "artist": "Billie Holiday", "track": "Strange Fruit", "year": 1939, "new_link": "https://www.youtube.com/watch?v=Web007rzSOI&list=RDWeb007rzSOI"},
    {"pack": "jazz-blues", "artist": "Frank Sinatra", "track": "Fly Me to the Moon", "year": 1964, "new_link": "https://www.youtube.com/watch?v=JYuyWrkwpok&list=RDJYuyWrkwpok"},
    {"pack": "jazz-blues", "artist": "Muddy Waters", "track": "Hoochie Coochie Man", "year": 1954, "new_link": "https://www.youtube.com/watch?v=e_l6A7krjrQ&list=RDe_l6A7krjrQ"},
    {"pack": "jazz-blues", "artist": "Amy Winehouse", "track": "Back to Black", "year": 2006, "new_link": "https://www.youtube.com/watch?v=TJAfLE39ZZ8&list=RDTJAfLE39ZZ8"},
    {"pack": "jazz-blues", "artist": "Benny Goodman", "track": "Sing, Sing, Sing", "year": 1937, "new_link": "https://www.youtube.com/watch?v=u_E0UVNtJ9Y&list=RDu_E0UVNtJ9Y"},
    {"pack": "jazz-blues", "artist": "Cab Calloway", "track": "Minnie the Moocher", "year": 1931, "new_link": "https://www.youtube.com/watch?v=8mq4UT4VnbE&list=RD8mq4UT4VnbE"},
    {"pack": "jazz-blues", "artist": "Peggy Lee", "track": "Fever", "year": 1958, "new_link": "https://www.youtube.com/watch?v=REryc1TpeY8&list=RDREryc1TpeY8"},
    {"pack": "jazz-blues", "artist": "Horace Silver", "track": "Song for My Father", "year": 1965, "new_link": "https://www.youtube.com/watch?v=mKf1x3CALAE&list=RDmKf1x3CALAE"},
    {"pack": "kids-disney", "artist": "Céline Dion & Peabo Bryson", "track": "Beauty and the Beast", "year": 1991, "new_link": "https://www.youtube.com/watch?v=ippaCca4L6A&list=RDippaCca4L6A"},
    {"pack": "kids-disney", "artist": "Auli'i Cravalho", "track": "How Far I'll Go", "year": 2016, "new_link": "https://www.youtube.com/watch?v=cPAbx5kgCJo&list=RDcPAbx5kgCJo"},
    {"pack": "kids-disney", "artist": "Dwayne Johnson", "track": "You're Welcome", "year": 2016, "new_link": "https://www.youtube.com/watch?v=79DijItQXMM&list=RD79DijItQXMM"},
    {"pack": "kids-disney", "artist": "Adassa, Stephanie Beatriz, et al.", "track": "We Don't Talk About Bruno", "year": 2021, "new_link": "https://www.youtube.com/watch?v=bvWRMAU6V-c&list=RDbvWRMAU6V-c"},
    {"pack": "kids-disney", "artist": "Benjamin Bratt", "track": "Remember Me", "year": 2017, "new_link": "https://www.youtube.com/watch?v=YexJzu9aSZ0&list=RDYexJzu9aSZ0"},
    {"pack": "kids-disney", "artist": "Donna Murphy", "track": "Mother Knows Best", "year": 2010, "new_link": "https://www.youtube.com/watch?v=-7jWt3JvJto&list=RD-7jWt3JvJto"},
    {"pack": "kids-disney", "artist": "Keith David", "track": "Friends on the Other Side", "year": 2009, "new_link": "https://www.youtube.com/watch?v=1BgfG4qEdxg&list=RD1BgfG4qEdxg"},
    {"pack": "kids-disney", "artist": "Peggy Lee", "track": "He's a Tramp", "year": 1955, "new_link": "https://www.youtube.com/watch?v=djwsBmqtBTw&list=RDdjwsBmqtBTw"},
    {"pack": "kids-disney", "artist": "Cliff Edwards", "track": "When You Wish Upon a Star", "year": 1940, "new_link": "https://www.youtube.com/watch?v=oTot6Kr2Q6s&list=RDoTot6Kr2Q6s"},
    {"pack": "kids-disney", "artist": "Samuel E. Wright", "track": "Under the Sea", "year": 1989, "new_link": "https://www.youtube.com/watch?v=GC_mV1IpjWA&list=RDGC_mV1IpjWA"},
    {"pack": "kids-disney", "artist": "Ilene Woods", "track": "A Dream Is a Wish Your Heart Makes", "year": 1950, "new_link": "https://www.youtube.com/watch?v=Kp7_6YBix30&list=RDKp7_6YBix30"},
    {"pack": "kids-disney", "artist": "Mary Costa & Bill Shirley", "track": "Once Upon a Dream", "year": 1959, "new_link": "https://www.youtube.com/watch?v=TXbHShUnwxY&list=RDTXbHShUnwxY"},
    {"pack": "kids-disney", "artist": "Adriana Caselotti", "track": "Someday My Prince Will Come", "year": 1937, "new_link": "https://www.youtube.com/watch?v=KrtWu8eBBek&list=RDKrtWu8eBBek"},
    {"pack": "kids-disney", "artist": "Lea Salonga", "track": "Reflection", "year": 1998, "new_link": "https://www.youtube.com/watch?v=NTlSFWHkJgk&list=RDNTlSFWHkJgk"},
    {"pack": "kids-disney", "artist": "Donny Osmond", "track": "I'll Make a Man Out of You", "year": 1998, "new_link": "https://www.youtube.com/watch?v=elBKil5zE2g&list=RDelBKil5zE2g"},
    {"pack": "kids-disney", "artist": "Tawatha Agee, Lillias White, et al.", "track": "Zero to Hero", "year": 1997, "new_link": "https://www.youtube.com/watch?v=L9gYEEpu1Yk&list=RDL9gYEEpu1Yk"},
    {"pack": "kids-disney", "artist": "Randy Newman", "track": "You've Got a Friend in Me", "year": 1995, "new_link": "https://www.youtube.com/watch?v=1MPZRcyTrcU&list=RD1MPZRcyTrcU"},
    {"pack": "metal-hardcore", "artist": "Metallica", "track": "Enter Sandman", "year": 1991, "new_link": "https://www.youtube.com/watch?v=CD-E-LDc384&list=RDCD-E-LDc384"},
    {"pack": "metal-hardcore", "artist": "Iron Maiden", "track": "The Trooper", "year": 1983, "new_link": "https://www.youtube.com/watch?v=X4bgXH3sJ2Q&list=RDX4bgXH3sJ2Q"},
    {"pack": "metal-hardcore", "artist": "Pantera", "track": "Walk", "year": 1992, "new_link": "https://www.youtube.com/watch?v=AkFqg5wAuFk&list=RDAkFqg5wAuFk"},
    {"pack": "metal-hardcore", "artist": "System of a Down", "track": "Chop Suey!", "year": 2001, "new_link": "https://www.youtube.com/watch?v=CSvFpBOe8eY&list=RDCSvFpBOe8eY"},
    {"pack": "metal-hardcore", "artist": "Rammstein", "track": "Du Hast", "year": 1997, "new_link": "https://www.youtube.com/watch?v=W3q8Od5qJio&list=RDW3q8Od5qJio"},
    {"pack": "metal-hardcore", "artist": "Disturbed", "track": "Down with the Sickness", "year": 2000, "new_link": "https://www.youtube.com/watch?v=09LTT0xwdfw&list=RD09LTT0xwdfw"},
    {"pack": "metal-hardcore", "artist": "Dream Theater", "track": "Pull Me Under", "year": 1992, "new_link": "https://www.youtube.com/watch?v=mipc-JxrhRk&list=RDmipc-JxrhRk"},
    {"pack": "metal-hardcore", "artist": "Nine Inch Nails", "track": "Closer", "year": 1994, "new_link": "https://www.youtube.com/watch?v=9-5IIx4R6E8&list=RD9-5IIx4R6E8"},
    {"pack": "metal-hardcore", "artist": "Marilyn Manson", "track": "The Beautiful People", "year": 1996, "new_link": "https://www.youtube.com/watch?v=Ypkv0HeUvTc&list=RDYpkv0HeUvTc"},
    {"pack": "metal-hardcore", "artist": "Cannibal Corpse", "track": "Hammer Smashed Face", "year": 1992, "new_link": "https://www.youtube.com/watch?v=vlgiWBCbCJk&list=RDvlgiWBCbCJk"},
    {"pack": "metal-hardcore", "artist": "Napalm Death", "track": "You Suffer", "year": 1987, "new_link": "https://www.youtube.com/watch?v=_-ywSPWu3K8&list=RD_-ywSPWu3K8"},
    {"pack": "metal-hardcore", "artist": "Black Flag", "track": "TV Party", "year": 1981, "new_link": "https://www.youtube.com/watch?v=psUOyXGacL0&list=RDpsUOyXGacL0"},
    {"pack": "Movie Hits", "artist": "Idina Menzel", "track": "Let It Go", "year": 2013, "new_link": "https://www.youtube.com/watch?v=YVVTZgwYwVo&list=RDYVVTZgwYwVo"},
    {"pack": "piano-ballads", "artist": "Elton John", "track": "Your Song", "year": 1970, "new_link": "https://www.youtube.com/watch?v=GlPlfCy1urI&list=RDGlPlfCy1urI"},
    {"pack": "piano-ballads", "artist": "Sam Smith", "track": "Writing's on the Wall", "year": 2015, "new_link": "https://www.youtube.com/watch?v=8jzDnsjYv9A&list=RD8jzDnsjYv9A"},
    {"pack": "piano-ballads", "artist": "James Arthur", "track": "Say You Won't Let Go", "year": 2016, "new_link": "https://www.youtube.com/watch?v=0yW7w8F2TVA&list=RD0yW7w8F2TVA"},
    {"pack": "piano-ballads", "artist": "Dean Lewis", "track": "Be Alright", "year": 2018, "new_link": "https://www.youtube.com/watch?v=I0czvJ_jikg&list=RDI0czvJ_jikg"},
    {"pack": "piano-ballads", "artist": "The Fray", "track": "How to Save a Life", "year": 2005, "new_link": "https://www.youtube.com/watch?v=cjVQ36NhbMk&list=RDcjVQ36NhbMk"},
    {"pack": "piano-ballads", "artist": "Daniel Powter", "track": "Bad Day", "year": 2005, "new_link": "https://www.youtube.com/watch?v=gH476CxJxfg&list=RDgH476CxJxfg"},
    {"pack": "piano-ballads", "artist": "Snow Patrol", "track": "Run (Piano Version)", "year": 2003, "new_link": "https://www.youtube.com/watch?v=AOBs8dU4Pb8&list=RDAOBs8dU4Pb8"},
    {"pack": "piano-ballads", "artist": "Gary Jules", "track": "Mad World", "year": 2001, "new_link": "https://www.youtube.com/watch?v=etSbOs3aUqI&list=RDetSbOs3aUqI"},
    {"pack": "piano-ballads", "artist": "Radiohead", "track": "No Surprises", "year": 1997, "new_link": "https://www.youtube.com/watch?v=u5CVsCnxyXg&list=RDu5CVsCnxyXg"},
    {"pack": "piano-ballads", "artist": "Hoobastank", "track": "The Reason", "year": 2004, "new_link": "https://www.youtube.com/watch?v=fV4DiAyExN0&list=RDfV4DiAyExN0"},
    {"pack": "piano-ballads", "artist": "Green Day", "track": "Wake Me Up When September Ends", "year": 2005, "new_link": "https://www.youtube.com/watch?v=pGhwBFYtn1s&list=RDpGhwBFYtn1s"},
    {"pack": "piano-ballads", "artist": "My Chemical Romance", "track": "Cancer", "year": 2006, "new_link": "https://www.youtube.com/watch?v=wc2s9skF_58&list=RDwc2s9skF_58"},
    {"pack": "Rock Anthems", "artist": "Journey", "track": "Don't Stop Believin'", "year": 1981, "new_link": "https://www.youtube.com/watch?v=x3idGV-7kSQ&list=RDx3idGV-7kSQ"},
    {"pack": "Rock Anthems", "artist": "KISS", "track": "Rock and Roll All Nite", "year": 1975, "new_link": "https://www.youtube.com/watch?v=K9paKQ9VdRA&list=RDK9paKQ9VdRA"},
    {"pack": "Schlager & Evergreens", "artist": "DJ Ötzi & Nik P.", "track": "Ein Stern (der deinen Namen trägt)", "year": 2007, "new_link": "https://www.youtube.com/watch?v=2Ua9af7xC9c&list=RD2Ua9af7xC9c"},
    {"pack": "soul-funk", "artist": "James Brown", "track": "I Got You (I Feel Good)", "year": 1965, "new_link": "https://www.youtube.com/watch?v=pTdihu-mp90&list=RDpTdihu-mp90"},
    {"pack": "soul-funk", "artist": "Bill Withers", "track": "Ain't No Sunshine", "year": 1971, "new_link": "https://www.youtube.com/watch?v=Nuanwn3v-2I&list=RDNuanwn3v-2I"},
    {"pack": "soul-funk", "artist": "Otis Redding", "track": "(Sittin' On) The Dock of the Bay", "year": 1968, "new_link": "https://www.youtube.com/watch?v=rTVjnBo96Ug&list=RDrTVjnBo96Ug"},
    {"pack": "soul-funk", "artist": "Sam Cooke", "track": "A Change Is Gonna Come", "year": 1964, "new_link": "https://www.youtube.com/watch?v=wEBlaMOmKV4&list=RDwEBlaMOmKV4"},
    {"pack": "soul-funk", "artist": "The Temptations", "track": "My Girl", "year": 1964, "new_link": "https://www.youtube.com/watch?v=y3KJ7d2qBoA&list=RDy3KJ7d2qBoA"},
    {"pack": "soul-funk", "artist": "Jackson 5", "track": "I Want You Back", "year": 1969, "new_link": "https://www.youtube.com/watch?v=UvynvnxZJ3Q&list=RDUvynvnxZJ3Q"},
    {"pack": "soul-funk", "artist": "Earth, Wind & Fire", "track": "September", "year": 1978, "new_link": "https://www.youtube.com/watch?v=Gs069dndIYk&list=RDGs069dndIYk"},
    {"pack": "soul-funk", "artist": "Kool & The Gang", "track": "Celebration", "year": 1980, "new_link": "https://www.youtube.com/watch?v=3GwjfUFyY6M&list=RD3GwjfUFyY6M"},
    {"pack": "soul-funk", "artist": "Parliament", "track": "Give Up the Funk (Tear the Roof Off...)", "year": 1976, "new_link": "https://www.youtube.com/watch?v=od-5gCO_PGE&list=RDod-5gCO_PGE"},
    {"pack": "soul-funk", "artist": "Curtis Mayfield", "track": "Move On Up", "year": 1970, "new_link": "https://www.youtube.com/watch?v=A9RMr9KuVZo&list=RDA9RMr9KuVZo"},
    {"pack": "soul-funk", "artist": "Barry White", "track": "Can't Get Enough of Your Love, Babe", "year": 1974, "new_link": "https://www.youtube.com/watch?v=fPMoLEjM_K4&list=RDfPMoLEjM_K4"},
    {"pack": "soul-funk", "artist": "Bill Withers", "track": "Lovely Day", "year": 1977, "new_link": "https://www.youtube.com/watch?v=bEeaS6fuUoA&list=RDbEeaS6fuUoA"},
    {"pack": "soul-funk", "artist": "Gnarls Barkley", "track": "Crazy", "year": 2006, "new_link": "https://www.youtube.com/watch?v=-N4jf6rtyuw&list=RD-N4jf6rtyuw"},
    {"pack": "World, Reggae & Soul", "artist": "Toots & The Maytals", "track": "54-46 Was My Number", "year": 1968, "new_link": "https://www.youtube.com/watch?v=bjeCrgv1v9o&list=RDbjeCrgv1v9o"},
    {"pack": "World, Reggae & Soul", "artist": "Peter Tosh", "track": "Legalize It", "year": 1976, "new_link": "https://www.youtube.com/watch?v=6cIePqdz03A&list=RD6cIePqdz03A"},
    {"pack": "World, Reggae & Soul", "artist": "Shaggy", "track": "It Wasn't Me", "year": 2000, "new_link": "https://www.youtube.com/watch?v=sTMgX1PDGAE&list=RDsTMgX1PDGAE"},
    {"pack": "World, Reggae & Soul", "artist": "Sean Paul", "track": "Get Busy", "year": 2002, "new_link": "https://www.youtube.com/watch?v=oPQ3o14ksaM&list=RDoPQ3o14ksaM"},
    {"pack": "World, Reggae & Soul", "artist": "Erykah Badu", "track": "On & On", "year": 1997, "new_link": "https://www.youtube.com/watch?v=TW28iWV7nxE&list=RDTW28iWV7nxE"},
    {"pack": "World, Reggae & Soul", "artist": "Nina Simone", "track": "My Baby Just Cares for Me", "year": 1958, "new_link": "https://www.youtube.com/watch?v=eYSbUOoq4Vg&list=RDeYSbUOoq4Vg"},
    {"pack": "World, Reggae & Soul", "artist": "Bob Marley & The Wailers", "track": "Three Little Birds", "year": 1977, "new_link": "https://www.youtube.com/watch?v=HNBCVM4KbUM&list=RDHNBCVM4KbUM"},
    {"pack": "World, Reggae & Soul", "artist": "UB40", "track": "Red Red Wine", "year": 1983, "new_link": "https://www.youtube.com/watch?v=zXt56MB-3vc&list=RDzXt56MB-3vc"},
    {"pack": "World, Reggae & Soul", "artist": "Inner Circle", "track": "Sweat (A La La La La Long)", "year": 1992, "new_link": "https://www.youtube.com/watch?v=uc2UEfWjvo8&list=RDuc2UEfWjvo8"},
    {"pack": "World, Reggae & Soul", "artist": "Shaggy ft. Rikrok", "track": "It Wasn't Me", "year": 2000, "new_link": "https://www.youtube.com/watch?v=U48fb7Nx1A8&list=RDU48fb7Nx1A8"},
    {"pack": "World, Reggae & Soul", "artist": "James Brown", "track": "I Got You (I Feel Good)", "year": 1965, "new_link": "https://www.youtube.com/watch?v=pTdihu-mp90&list=RDpTdihu-mp90"},
]

def extract_youtube_id(link):
    if not link: return None
    # Match standard watch?v= format
    v_match = re.search(r"[?&]v=([^&]+)", link)
    if v_match:
        return v_match.group(1)
    # Match short youtu.be/ format
    be_match = re.search(r"youtu\.be/([^?&]+)", link)
    if be_match:
        return be_match.group(1)
    return link # Return as is if it looks like an ID

processed_data = []
for entry in raw_corrections:
    yt_id = extract_youtube_id(entry["new_link"])
    if yt_id:
        processed_data.append({
            "pack": entry["pack"],
            "artist": entry["artist"],
            "track": entry["track"],
            "year": entry["year"],
            "youtubeId": yt_id
        })

with open("/Users/volker/Phomu/Phomu/corrections.json", "w") as f:
    json.dump(processed_data, f, indent=2)

print(f"Consolidated {len(processed_data)} corrections into corrections.json")
